template: true
valuesFilePath: ./values.yml

resources:
  - name: {{ .Values.gitRepo.name }}
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.gitRepo.provider }}
      path: {{ .Values.gitRepo.path }}

  - name: {{ .Values.pipelines.name }}
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artifactory }}

pipelines:
  - name: {{ .Values.pipelines.name }}
    steps:
      - name: mvn_build
        type: MvnBuild
        configuration:
          sourceLocation: .
          mvnCommand: clean install -ntp
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: {{ .Values.gitRepo.name }}
          integrations:
            - name: {{ .Values.artifactory }}

      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          forceXrayScan: false
          inputSteps:
            - name: mvn_build
          outputResources:
            - name: {{ .Values.pipelines.name }}
